Repository SC-ECE/PYTHON-PROJECT, pull requests merged in 2023-01, with the labels that each got.

#1 Password Manager
  Password Manager/LICENSE
  Password Manager/README.md
  Password Manager/advance_search.py
  Password Manager/change_pin_page.py
  Password Manager/dark_mode_page.py
  Password Manager/decrypt_message.py
  Password Manager/email_page.py
  Password Manager/encyrpt_message.py
  Password Manager/installation.py
  Password Manager/main.py
  Password Manager/multiple_result.py
  Password Manager/new3.png
  Password Manager/new_account_page.py
  Password Manager/pass_manager_image.png
  Password Manager/saving_data.py
  Password Manager/search_page.py
Labels: Hard, Synapse

#3 Real Time Vehicle Detection
  Real Time Vehicle Detection/Readme.md
  Real Time Vehicle Detection/isCar.xml
  Real Time Vehicle Detection/main.py
  Real Time Vehicle Detection/video1.mp4
Labels: Medium, Synapse

#4 Image to Pencil Sketch
  Image to Pencil Sketch/Readme.md
  Image to Pencil Sketch/STEPS/1_original.jpg
  Image to Pencil Sketch/STEPS/2_grayscale.jpg
  Image to Pencil Sketch/STEPS/3_invert.jpg
  Image to Pencil Sketch/STEPS/4_blur.jpg
  Image to Pencil Sketch/STEPS/5_invertedblurry.jpg
  Image to Pencil Sketch/STEPS/6_sketch.jpg
  Image to Pencil Sketch/ben10.jpg
  Image to Pencil Sketch/main.py
Labels: Medium, Synapse

#5 Rock Paper Scissors Game
  Rock Paper Scissors Game/Readme.md
  Rock Paper Scissors Game/rock_paper_scissors.py
Labels: Easy, Synapse

#6 WaterColor Image Converter
  WaterColor Image Converter/Readme.md
  WaterColor Image Converter/app.py
Labels: Easy, Synapse

#8 Number guessing game
  Number guessing game/Readme.md
  Number guessing game/main.py
Labels: Easy, Synapse

#9 Create Digital Clock
  Create digital clock/Readme.md
  Create digital clock/main.py
Labels: Medium, Synapse

#12 Quiz
  Quiz-DB/README (1).md
  Quiz-DB/quiz.py
Labels: Easy, Synapse

#11 Two Player Game
  Two Player Game/Readme.md
  Two Player Game/main.py
Labels: Medium, Synapse

#10 PasswordGenerator
  PasswordGenerator/PasswordGenerator.py
  PasswordGenerator/README.md
  PasswordGenerator/passwords.txt
Labels: Easy, Synapse

#13 Sentiment Detector GUI
  Sentiment Detector GUI/Readme.md
  Sentiment Detector GUI/main.py
Labels: Medium, Synapse

#14 PythonMarksGradeSystem
  grade_system/README.md
  grade_system/grade.py
Labels: Medium, Synapse

#16 python commit
  Face recognitio DB/README (2).md
  Face recognitio DB/face_Recognition.py
Labels: Medium, Synapse

#18 Phone number tracking
  Number tracking DB/Number_tracking.py
  Number tracking DB/README (3).md
Labels: Easy, Synapse

#17 FLAMES Game
  FLAMES Game/Readme.md
  FLAMES Game/main.py
Labels: Medium, Synapse

#19 Rank Based Percentile Gui Calculator
  Rank Based Percentile Gui Calculator/Readme.md
  Rank Based Percentile Gui Calculator/main.py
Labels: Medium, Synapse

#20 Gui-based Snake and Ladder game
  Gui-based Snake and Ladder game/Readme.md
  Gui-based Snake and Ladder game/main.py
Labels: Medium, Synapse

#21 GUI Marksheet
  GUI Marksheet/Readme.md
  GUI Marksheet/main.py
Labels: Easy, Synapse

#22 Color Game
  Color Game/Readme.md
  Color Game/main.py
Labels: Easy, Synapse

#23 DigitalClock
  AnalogClock/AnalogClock.py
  AnalogClock/README.md
  DigitalClock/README.md
  DigitalClock/digitalclock.py
  PasswordGenerator/passwords.txt
Labels: Medium, Synapse

#25 Scientific Calculator
  Scientific Calculator/Readme.md
  Scientific Calculator/main.py
Labels: Medium, Synapse

#24 Tic Tac Toe Game
  Tic-Tac-Toe/README.md
  Tic-Tac-Toe/main.py
Labels: Easy, Synapse

#26 GUI Text Creator
  GUI Text Creator/README.md
  GUI Text Creator/main.py
Labels: Easy, Synapse

#27 To Do List App
  To Do List App/Readme.md
  To Do List App/main.py
Labels: Easy, Synapse

#28 Typing Tester
  TypingTester/README.md
  TypingTester/Typingtester.py
  TypingTester/words.txt
Labels: Easy, Synapse

#29 Add files via upload
  Guess The Number/Guess_number.py
  Guess The Number/README.md
  Guess The Number/best_score.txt
Labels: Medium, Synapse

#30 Drawing App
  Drawing App/Readme.md
  Drawing App/main.py
Labels: Easy, Synapse

#33 Face recognition based attendance system
  Face recognition based attendance system/README.md
  Face recognition based attendance system/haarcascade_frontalface_default.xml
  Face recognition based attendance system/main.py
Labels: Hard, Synapse

#32 Face Mesh
  Face_Mesh/Mrbean.jpg
  Face_Mesh/README.md
  Face_Mesh/annotated_image0.png
  Face_Mesh/faceddetection.py
Labels: Hard, Synapse

#31 GUI Based Restaurant Management System
  GUI Based Restaurant Management System/Readme.md
  GUI Based Restaurant Management System/restaurant.py
Labels: Medium, Synapse

#34 Typing Speed Tester
  Typing_Speed_Tester - DB/README (3).md
  Typing_Speed_Tester - DB/Typing_Speed_Tester.py
Labels: Synapse

#38 GUI based Quiz Application
  GUI based Quiz Application/Readme.md
  GUI based Quiz Application/main.py
  GUI based Quiz Application/question_model.py
  GUI based Quiz Application/quiz_brain.py
  GUI based Quiz Application/quiz_data.py
  GUI based Quiz Application/quiz_ui.py
Labels: Medium, Synapse

#37 Stone Paper Scissors
  Stone Paper Scissors/README.md
  Stone Paper Scissors/Stone_Paper_Scissors.py
Labels: Easy, Synapse

#36 Music Player
  Music player/README.md
  Music player/main.py
Labels: Medium, Synapse

#40 Whatsapp Bot
  Whatsapp Bot using selenium/README.md
  Whatsapp Bot using selenium/whatsapp.py
Labels: Medium, Synapse

#39 Virtual Mouse
  IndianFlagHosting/README.md
  IndianFlagHosting/main.py
  README.md
  VirtualMouse/README.md
  VirtualMouse/virtualmouse.py
Labels: Hard, Synapse

#41 Plagiarism Checker
  Plagiarism Checker/README.md
  Plagiarism Checker/plag.py
  Plagiarism Checker/req.txt
  Plagiarism Checker/templates/index.html
Labels: Medium, Synapse

#42 Youtube Video Downloader
  Youtube Video Downloader/Readme.md
  Youtube Video Downloader/youtube.png
  Youtube Video Downloader/yt-downloader.py
Labels: Medium, Synapse

#43 Sudoku Solver
  Sudoku Solver/README.md
  Sudoku Solver/SudokuGUI.py
  Sudoku Solver/assets/Entering Values.gif
  Sudoku Solver/assets/Visualizer.gif
  Sudoku Solver/assets/thumbnail.png
  Sudoku Solver/requirements.txt
  Sudoku Solver/sudokutools.py
Labels: Medium, Synapse

#44 HandDetector_Python
  HandLandmarks_Mediapipe/README.md
  HandLandmarks_Mediapipe/main.py
  IndianFlagHosting/README.md
  IndianFlagHosting/main.py
Labels: Medium, Synapse
